make simple:
	gcc -Wall restaurant.c -o restaurant -lpthread -lrt
	gcc -Wall cook.c -o cook -lpthread -lrt
	gcc -Wall deliverer.c -o deliverer -lpthread -lrt

make test:
	make simple
	./restaurant 7 6